tap "robotsandpencils/made"

brew "ag"
brew "anyenv"
brew "aria2"
brew "asdf"
brew "awscli"
brew "carthage"
brew "direnv"
brew "gh"
brew "ghq"
brew "git"
brew "git-lfs"
brew "hugo"
brew "jq"
brew "lutzifer/homebrew-tap/keyboardSwitcher"
brew "mas"
brew "mint"
brew "peco"
brew "qrencode"
brew "robotsandpencils/made/xcodes"
brew "tig"
brew "tmux"
brew "vim"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "bartender"
cask "discord"
cask "docker"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "jetbrains-toolbox"
cask "raycast"
cask "slack"
cask "spotify"
cask "visual-studio-code"

mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Run Cat", id: 1429033973
mas "The Unarchiver", id: 425424353
